/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihanGUI;

/**
 *
 * @author Asus
 */
public class Kalkulator extends javax.swing.JFrame {

    String angka = " ";
    double jumlah, angka1,angka2;
    int pilih;
    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bempat = new javax.swing.JButton();
        bkurleb = new javax.swing.JButton();
        bdua = new javax.swing.JButton();
        btiga = new javax.swing.JButton();
        blima = new javax.swing.JButton();
        btujuh = new javax.swing.JButton();
        bdelapan = new javax.swing.JButton();
        bsatu = new javax.swing.JButton();
        benam = new javax.swing.JButton();
        bnol = new javax.swing.JButton();
        btitik = new javax.swing.JButton();
        bsembilan = new javax.swing.JButton();
        bhasil = new javax.swing.JButton();
        bc = new javax.swing.JButton();
        bpersen = new javax.swing.JButton();
        bakar = new javax.swing.JButton();
        bce = new javax.swing.JButton();
        btambah = new javax.swing.JButton();
        bkurang = new javax.swing.JButton();
        bkali = new javax.swing.JButton();
        bbagi = new javax.swing.JButton();
        bsatuperx = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        tflayar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULATOR");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bempat.setBackground(new java.awt.Color(0, 102, 102));
        bempat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bempat.setText("4");
        bempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bempatActionPerformed(evt);
            }
        });
        jPanel1.add(bempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 60, 60));

        bkurleb.setText("±");
        bkurleb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkurlebActionPerformed(evt);
            }
        });
        jPanel1.add(bkurleb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 60, 60));

        bdua.setBackground(new java.awt.Color(0, 102, 102));
        bdua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bdua.setText("2");
        bdua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bduaActionPerformed(evt);
            }
        });
        jPanel1.add(bdua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 60, 60));

        btiga.setBackground(new java.awt.Color(0, 102, 102));
        btiga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btiga.setText("3");
        btiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btigaActionPerformed(evt);
            }
        });
        jPanel1.add(btiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 60, 60));

        blima.setBackground(new java.awt.Color(0, 102, 102));
        blima.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blima.setText("5");
        blima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blimaActionPerformed(evt);
            }
        });
        jPanel1.add(blima, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 60, 60));

        btujuh.setBackground(new java.awt.Color(0, 102, 102));
        btujuh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btujuh.setText("7");
        btujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btujuhActionPerformed(evt);
            }
        });
        jPanel1.add(btujuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 60, 60));

        bdelapan.setBackground(new java.awt.Color(0, 102, 102));
        bdelapan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bdelapan.setText("8");
        bdelapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdelapanActionPerformed(evt);
            }
        });
        jPanel1.add(bdelapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 60, 60));

        bsatu.setBackground(new java.awt.Color(0, 102, 102));
        bsatu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bsatu.setText("1");
        bsatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsatuActionPerformed(evt);
            }
        });
        jPanel1.add(bsatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 60, 60));

        benam.setBackground(new java.awt.Color(0, 102, 102));
        benam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        benam.setText("6");
        benam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benamActionPerformed(evt);
            }
        });
        jPanel1.add(benam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 60, 60));

        bnol.setBackground(new java.awt.Color(0, 102, 102));
        bnol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bnol.setText("0");
        bnol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnolActionPerformed(evt);
            }
        });
        jPanel1.add(bnol, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 60, 60));

        btitik.setText(".");
        btitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btitikActionPerformed(evt);
            }
        });
        jPanel1.add(btitik, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 60, 60));

        bsembilan.setBackground(new java.awt.Color(0, 102, 102));
        bsembilan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bsembilan.setText("9");
        bsembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsembilanActionPerformed(evt);
            }
        });
        jPanel1.add(bsembilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 60, 60));

        bhasil.setText("=");
        bhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhasilActionPerformed(evt);
            }
        });
        jPanel1.add(bhasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 60, 130));

        bc.setText("C");
        bc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcActionPerformed(evt);
            }
        });
        jPanel1.add(bc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 60, 40));

        bpersen.setText("%");
        bpersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpersenActionPerformed(evt);
            }
        });
        jPanel1.add(bpersen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, 40));

        bakar.setText("√");
        bakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakarActionPerformed(evt);
            }
        });
        jPanel1.add(bakar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 60, 40));

        bce.setText("CE");
        bce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bceActionPerformed(evt);
            }
        });
        jPanel1.add(bce, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 40));

        btambah.setText("+");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });
        jPanel1.add(btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 60, 40));

        bkurang.setText("-");
        bkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkurangActionPerformed(evt);
            }
        });
        jPanel1.add(bkurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 60, 40));

        bkali.setText("×");
        bkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkaliActionPerformed(evt);
            }
        });
        jPanel1.add(bkali, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 60, 40));

        bbagi.setText("÷");
        bbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbagiActionPerformed(evt);
            }
        });
        jPanel1.add(bbagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 60, 40));

        bsatuperx.setText("1/x");
        bsatuperx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsatuperxActionPerformed(evt);
            }
        });
        jPanel1.add(bsatuperx, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 60, 40));

        bhapus.setText("←");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel1.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 60, 40));

        tflayar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tflayar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tflayar.setEnabled(false);
        jPanel1.add(tflayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bduaActionPerformed
        // TODO add your handling code here:
        angka += "2";
        tflayar.setText(angka);
    }//GEN-LAST:event_bduaActionPerformed

    private void bhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhasilActionPerformed
        // TODO add your handling code here:
        switch(pilih){
        case 1:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 + angka2;
            angka = Double.toString(jumlah);
            tflayar.setText(angka);
            break;
        case 2:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 - angka2;
            angka = Double.toString(jumlah);
            tflayar.setText(angka);
            break;
        case 3:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 * angka2;
            angka = Double.toString(jumlah);
            tflayar.setText(angka);
            break;
        case 4:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 / angka2;
            angka = Double.toString(jumlah);
            tflayar.setText(angka);
            break;
        case 5 :
            jumlah = angka1/100;
            angka = Double.toString(jumlah);
            tflayar.setText(angka);
            break;
        case 6 :
            jumlah = Math.sqrt(angka1);
            angka = Double.toString(jumlah);
            tflayar.setText(angka);
            break;
        case 7 :
            jumlah = 1/angka1 ;
            angka = Double.toString(jumlah);
            tflayar.setText(angka);
            break;
        case 8 :
            angka2= Double.parseDouble(angka);
            jumlah = angka1- angka2;
            angka = Double.toString(jumlah);
            tflayar.setText("-"+angka); 
            break;
            default:
            break;
        }
    }//GEN-LAST:event_bhasilActionPerformed

    private void bakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakarActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        tflayar.setText("√");
        angka = " ";
        pilih = 6;
    }//GEN-LAST:event_bakarActionPerformed

    private void benamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benamActionPerformed
        // TODO add your handling code here:
        angka += "6";
        tflayar.setText(angka);
    }//GEN-LAST:event_benamActionPerformed

    private void btujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btujuhActionPerformed
        // TODO add your handling code here:
        angka += "7";
        tflayar.setText(angka);
    }//GEN-LAST:event_btujuhActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        // TODO add your handling code here:
        angka1= Double.parseDouble(angka);
        tflayar.setText("+");
        angka= " ";
        pilih=1;
    }//GEN-LAST:event_btambahActionPerformed

    private void bkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkurangActionPerformed
        // TODO add your handling code here:
        angka1= Double.parseDouble(angka);
        tflayar.setText("-");
        angka="";
        pilih=2;
    }//GEN-LAST:event_bkurangActionPerformed

    private void bkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkaliActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        tflayar.setText("×");
        angka="";
        pilih=3;
    }//GEN-LAST:event_bkaliActionPerformed

    private void bbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbagiActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        tflayar.setText("÷");
        angka="";
        pilih=4;
        
    }//GEN-LAST:event_bbagiActionPerformed

    private void bsatuperxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsatuperxActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        tflayar.setText(" ");
        angka = " ";
        pilih = 7;
    }//GEN-LAST:event_bsatuperxActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        angka = angka.substring(0,angka.length()-1);
        tflayar.setText(angka);
    }//GEN-LAST:event_bhapusActionPerformed

    private void bceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bceActionPerformed
        // TODO add your handling code here:
        tflayar.setText("");
        angka1=0.0;
        angka2=0.0;
        jumlah=0.0;
        angka = " ";
    }//GEN-LAST:event_bceActionPerformed

    private void bnolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnolActionPerformed
        // TODO add your handling code here:
        angka += "0";
        tflayar.setText(angka);
    }//GEN-LAST:event_bnolActionPerformed

    private void bsatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsatuActionPerformed
        // TODO add your handling code here:
        angka += "1";
        tflayar.setText(angka);
    }//GEN-LAST:event_bsatuActionPerformed

    private void btigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btigaActionPerformed
        // TODO add your handling code here:
        angka += "3";
        tflayar.setText(angka);
    }//GEN-LAST:event_btigaActionPerformed

    private void bempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bempatActionPerformed
        // TODO add your handling code here:
        angka += "4";
        tflayar.setText(angka);
    }//GEN-LAST:event_bempatActionPerformed

    private void blimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blimaActionPerformed
        // TODO add your handling code here:
        angka += "5";
        tflayar.setText(angka);
    }//GEN-LAST:event_blimaActionPerformed

    private void bdelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdelapanActionPerformed
        // TODO add your handling code here:
        angka += "8";
        tflayar.setText(angka);
    }//GEN-LAST:event_bdelapanActionPerformed

    private void bsembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsembilanActionPerformed
        // TODO add your handling code here:
        angka += "9";
        tflayar.setText(angka);
    }//GEN-LAST:event_bsembilanActionPerformed

    private void btitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btitikActionPerformed
        // TODO add your handling code here:
        angka += ".";
        tflayar.setText(angka);
    }//GEN-LAST:event_btitikActionPerformed

    private void bcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcActionPerformed
        // TODO add your handling code here:
        tflayar.setText("");
        angka1=0.0;
        angka2=0.0;
        jumlah=0.0;
        angka = "";
    }//GEN-LAST:event_bcActionPerformed

    private void bkurlebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkurlebActionPerformed
        // TODO add your handling code here:
        if(!angka.contains("-"))
            angka = "-" +angka;
        else
            angka = angka.substring(1,angka.length());
        tflayar.setText(angka);
        pilih = 8;
    }//GEN-LAST:event_bkurlebActionPerformed

    private void bpersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpersenActionPerformed
        // TODO add your handling code here
        angka1 = Double.parseDouble(angka);
        tflayar.setText("%");
        angka = " ";
        pilih = 5;
    }//GEN-LAST:event_bpersenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bakar;
    private javax.swing.JButton bbagi;
    private javax.swing.JButton bc;
    private javax.swing.JButton bce;
    private javax.swing.JButton bdelapan;
    private javax.swing.JButton bdua;
    private javax.swing.JButton bempat;
    private javax.swing.JButton benam;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bhasil;
    private javax.swing.JButton bkali;
    private javax.swing.JButton bkurang;
    private javax.swing.JButton bkurleb;
    private javax.swing.JButton blima;
    private javax.swing.JButton bnol;
    private javax.swing.JButton bpersen;
    private javax.swing.JButton bsatu;
    private javax.swing.JButton bsatuperx;
    private javax.swing.JButton bsembilan;
    private javax.swing.JButton btambah;
    private javax.swing.JButton btiga;
    private javax.swing.JButton btitik;
    private javax.swing.JButton btujuh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tflayar;
    // End of variables declaration//GEN-END:variables
}
